#!/bin/sh

# script/setup: Set up application for the first time after cloning

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> App is now ready to go!"

# Extra things to do
# - git tags
# - updatedb for locate
# - etc
