#!/bin/sh

# script/setup: Set up application for the first time after cloning

set -e

cd "$(dirname "$0")/.."

# Setup sub remotes. All readonly for now (bulk of workflow).
git remote add vxl	https://github.com/vxl/vxl.git
git remote add vxd	https://github.com/rfabbri/vxd.git
git remote add utils git://git.code.sf.net/p/labmacambira/utils

# Fetch in parallel
git fetch vxl &
git fetch vxd &
git fetch utils &

# Basic deps
script/bootstrap

# Setup branches
git branch utils-master origin/utils-master
git branch vxl-master origin/vxl-master
git branch vxd-master origin/vxd-master

ln -s vxl-bin-dbg vxl-bin
ln -s vxd-bin-dbg vxd-bin

# wait fetches to finish
wait

# Setup separate hardlinked clones for each sub package, for history searching,
# Or for those who prefer it. This should not consume more space (hardlinks).
git clone $PWD vxl-orig
cd vxl-orig
git checkout -b vxl-master origin/vxl-master
git remote add vxl	https://github.com/vxl/vxl.git

git clone $PWD vxd-orig
cd vxd-orig
git checkout -b vxd-master origin/vxd-master
git remote add vxd	https://github.com/rfabbri/vxd.git

echo "==> VPE is now ready to go!"

# Extra things to do
# - git tags
