#!/bin/sh

# setup: Set up application for the first time after cloning

set -e

cd "$(dirname "$0")/../.."

./setup-for-use

echo '==> Seting up sub remotes. All readonly for now (bulk of workflow).'
git remote add vxl	https://github.com/vxl/vxl.git
git remote add vxd	https://github.com/rfabbri/vxd.git
git remote add utils git://git.code.sf.net/p/labmacambira/utils

# Fetch in parallel
git fetch vxl &
git fetch vxd &
git fetch utils &

# Basic deps
echo '==> Installing dependencies.'
scripts/devsetup/bootstrap

# Setup branches
echo '==> Setting up branches and symlinks.'
git branch utils-master origin/utils-master
git branch vxl-master origin/vxl-master
git branch vxd-master origin/vxd-master

echo '==> Setting up hardlinked clones for each subpackage.'
# Setup separate hardlinked clones for each sub package, for history searching,
# Or for those who prefer it. This should not consume more space (hardlinks).
git clone $PWD vxl-orig &
git clone $PWD vxd-orig &

# wait fetches and clones to finish
wait

cd vxl-orig
git checkout -b vxl-master origin/vxl-master
git remote add vxl	https://github.com/vxl/vxl.git

cd ../vxd-orig
git checkout -b vxd-master origin/vxd-master
git remote add vxd	https://github.com/rfabbri/vxd.git

cd ..

# Extra things to do
# - git tags
