#!/bin/sh
#
# DESCRIPTION
#
#   This script was based on the instructions from
#     http://wiki.nosdigitais.teia.org.br/Configuring_Ubuntu_for_Programming
#
# USAGE
#   
#   sudo sh configure-ubuntu-for-programming
#
# TODO
#
#   Scheme to download all packages into one computer and reuse them for the
#   remaining computers of a large Lab, in order to save time and bandwidth.
#
# AUTHOR
#   Ricardo Fabbri, Lab Macambira Team, UERJ IPRJ Team
#
apt-get -y install kdenlive meshlab kino texlive-full blender konqueror konq-plugins glade gtk-gnutella emacs scilab octave ipython ddd xmaxima gap r-base r-base-dev r-recommended gnuplot imagemagick inkscape gimp digikam compizconfig-settings-manager pitivi python-kiwi apache2 ssh recordmydesktop mplayer mpv gxine vlc ffmpeg puredata puredata-import git-core git-svn git-cvs kubuntu-full amarok cmake cmake-curses-gui autoconf automake libtool ekiga chromium-browser konsole  gitk gitg irssi xfig gv amule amule-emc qbittorrent nicotine gtk-gnutella kubuntu-full kubuntu-desktop vim-gnome mesa-utils dconf-tools sshfs pdftk libmagick++-dev gimp-data-extras gimp-plugin-registry gnome-tweak-tool v4l-utils php synaptic libv4l-dev swig tcllib ardour audacity audacious jackd qjackctl unrar unison-gtk libproc-processtable-perl guvcview exuberant-ctags gthumb xzgv apt-file apt-rdepends unity-tweak-tool okular

# if you get any error, remove the package one by one.

apt-get -y build-dep blender evince okular mplayer mpv gimp libreoffice empathy kino vlc gxine puredata lmms inkscape

# if you get any error, remove the package one by one.
# Even if you get a "but it is not going to be installed" message, remove the
# package from the above line. For Ubuntu 15.10, I removed scilab and firefox.
# But you can try them anyways
#
#
# Try:
# apt-get -y build-dep scilab
# apt-get -y build-dep firefox
#

# Remove the unified menu
#
apt-get remove indicator-appmenu 

# Diodon clipboard history manager
#
# Newer ubuntu ship this by default
# For older ubuntu, you might have to uncomment the following lines
#sudo add-apt-repository ppa:diodon-team/stable
#sudo apt-get update
sudo apt-get -y install diodon
echo Tip: go to diodon preferences and set all options

# Multiload system usage indicator
# Newer ubuntu ship this by default
# For older ubuntu, you might have to uncomment the following lines
#sudo add-apt-repository ppa:indicator-multiload/stable-daily
#sudo apt-get update
sudo apt-get -y install indicator-multiload

# apt-file find example.h will locate package that has it
sudo apt-file update

# install the latest stable git possible
# this is important for certain features, specially for subtrees
# and submodules. Also cool for diff highlighting and other sugar

sudo apt-add-repository ppa:git-core/ppa
sudo apt-get update
sudo apt-get upgrade git

# so you can use locate to search for files
sudo updatedb


# enable workspaces, linearly for consistency with Mac OS workflows
gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 4
gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize 1


# Tweaks
#  ...... and this is why Linux is much more professional than Mac OS for
#  advanced (truly pro) users
#
# Run:
#   unity-tweak-tool
# And enable auto-hide for the launcher
#
# Enable focus follow mouse. This is excellent for productivity as you can
# copy paste between windows without clicking, without messing up window order- R. Fabbri
# - Go to General -> Additional. Focus mode: Sloppy or Mouse.
# Basically try out sloppy or mouse, see what works with Alt-Tab etc.

# Firefox tweaks
# Reduce firefox font and menu sizes
#
# Reduce UI size for Unity
