#!/bin/sh
#gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dDownsampleColorImages=true -dColorImageResolution=150 -dNOPAUSE  -dBATCH -sOutputFile=$2 $1

set +x

pdf2ps $1 /tmp/$$-out.ps
ps2pdf /tmp/$$-out.ps $1
