#!/bin/sh

# script/setup-for-development: 
# Start a new vxl programming environment (VPE), after a new git clone
#

set -e

if test "`git remote | grep vxl`" = 'vxl'; then
  echo 'Looks like this repository has already been setup.'
  exit
fi

# Install dependencies,
# Add user-independent branches, remotes etc
scripts/devsetup/setup

# User-dependent settings: git email, etc
scripts/devsetup/setup-user

sudo -v   # prompts for password
sudo updatedb&

# Last thing: tips and suggestions
scripts/devsetup/tips | less

echo waiting for updatedb to finish up
wait
