#!/bin/sh
#
# DESCRIPTION
#
#   This script was based on the instructions from
#     http://wiki.nosdigitais.teia.org.br/Configuring_Ubuntu_for_Programming
#
# USAGE
#   
#   sudo sh configure-ubuntu-for-programming
#
# TODO
#
#   Scheme to download all packages into one computer and reuse them for the
#   remaining computers of a large Lab, in order to save time and bandwidth.
#
# AUTHOR
#   Ricardo Fabbri, Lab Macambira Team, UERJ IPRJ Team
#

apt-get -y install quickly kdenlive kino texlive-full blender kile konqueror konq-plugins  glade gtk-gnutella freemind emacs scilab octave ipython ddd xmaxima gap r-base r-base-dev r-recommended gnuplot imagemagick inkscape gimp digikam compizconfig-settings-manager pitivi python-kiwi apache2 ssh recordmydesktop mplayer gxine vlc ffmpeg puredata puredata-import git-core git-svn git-cvs kubuntu-full amarok cmake cmake-curses-gui autoconf automake libtool ekiga chromium-browser konsole  gitk gitg irssi xfig gv amule amule-emc qbittorrent nicotine gtk-gnutella kubuntu-full kubuntu-desktop vim-gnome mesa-utils dconf-tools sshfs pdftk libmagick++-dev gimp-data-extras gimp-plugin-registry gnome-tweak-tool v4l-utils synaptic libv4l-dev swig tcllib ardour audacity audacious jackd qjackctl unrar unison-gtk php5 libproc-processtable-perl guvcview exuberant-ctags

apt-get -y build-dep scilab evince okular mplayer gimp libreoffice firefox empathy kino vlc gxine puredata  lmms

apt-get remove indicator-appmenu 

sudo add-apt-repository ppa:diodon-team/stable
sudo apt-get update
sudo apt-get -y install diodon

sudo add-apt-repository ppa:indicator-multiload/stable-daily
sudo apt-get update
sudo apt-get -y install indicator-multiload
