#!/bin/sh
# move git-tracked files to destination
#
# USAGE
#   git-mv-tracked path-from path-to

set -x
#tmpf=/tmp/git-mv-tracked-$$.tar
git archive HEAD $1 | tar xf - -C $2
#trap 'rm -f $tmpf; exit 1' 1 2 15
#rm -f $tmpf
