#!/bin/sh
# scans using SANE on Linux and OSX

set -x
case $# in
    1) fname=$1
    ;;
    0)  num=`ls|grep -o '[0-9].*[0-9].'| cut -f 1 -d .|sort -n|tail -n 1`
        num=`echo $num + 1|bc`
        num=`printf "%03d" $num`
        fname=out${num}.pnm
    ;;
    *) echo 'Usage: myscan [file name]'
esac

scanimage --device hpaio:/usb/psc_1310_series?serial=BR51R3G0STO2 > $fname
