#!/bin/sh
# For getting projects to the new Cmake lowcase style
# Taken from vxl git log

cmake --help-command-list \
 | grep -v "cmake version" \
 | while read c; do
     echo 's/\b'"$(echo $c | gtr '[:lower:]' '[:upper:]')"'\(\s*\)(/'"$c"'\1(/g'
   done >convert.sed \
 && git ls-files -z -- bootstrap '*.cmake' '*.cmake.in' '*CMakeLists.txt' \
 | xargs -0 gsed -i -f convert.sed \
 && rm convert.sed
