#!/bin/sh

# script/setup-for-development: 
# Start a new vxl programming environment (VPE), after a new git clone
#

set -e

cd "$(dirname "$0")/.."

# Install dependencies,
# Add user-independent branches, remotes etc
devsetup/setup

# User-dependent settings: git email, etc
devsetup/setup-user

sudo updatedb&

# Last thing: tips and suggestions
devsetup/tips | less

echo waiting for updatedb to finish up
wait
